name: CI
on:
  push:
    branches-ignore:
      - '**'
jobs:
  build-linux:
    name: Linux - Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        shell: bash
        run: |
          sudo apt install -y gcc g++ gcc-multilib g++-multilib
      - name: Build
        shell: bash
        run: >
          chmod -R 755 *

          ./Compile.sh

          mkdir $GITHUB_WORKSPACE/Release/addons/amxmodx/modules/

          mv $GITHUB_WORKSPACE/buttonsmanager_amxx_i386.so $GITHUB_WORKSPACE/Release/addons/amxmodx/modules/buttonsmanager_amxx_i386.so

          tar -zcvf buttonsmanager.tar.gz Release
    
      - name: "Determine tag"
        id: "determine-tag"
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/tags/}\""

      - name: "Create release"
        id: "create-release"
        uses: "actions/create-release@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          draft: false
          prerelease: false
          release_name: "${{ steps.determine-tag.outputs.tag }}"
          tag_name: "${{ steps.determine-tag.outputs.tag }}"

      - name: "Upload Release Asset"
        uses: "actions/upload-release-asset@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ./buttonsmanager.tar.gz
          asset_name: buttonsmanager.tar.gz
          asset_content_type: application/tar+gzip
          
