name: Build and attach assets on release published
on:
  push:
    branches-ignore:
      - '**'
jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        shell: bash
        run: sudo apt install -y gcc g++ gcc-multilib g++-multilib
      - name: Get the version
        id: get_version
        run: echo ::set-output name=GIT_TAG_VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build
        shell: bash
        run: |
          chmod -R 755 *
          echo ${{ steps.get_version.outputs.GIT_TAG_VERSION }}
          export MODULE_VERSION_A="$(echo | cat $GITHUB_WORKSPACE/.version)"
          echo ${MODULE_VERSION_A}
          ./Compile.sh ${GIT_TAG_VERSION}
          mkdir $GITHUB_WORKSPACE/Release/addons/amxmodx/modules/
          mv $GITHUB_WORKSPACE/buttonsmanager_amxx_i386.so $GITHUB_WORKSPACE/Release/addons/amxmodx/modules/buttonsmanager_amxx_i386.so
          tar -zcvf buttonsmanager.tar.gz Release

      - name: "Get upload url"
        run: echo "::set-output name=upload_url::https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets{?name,label}"
        id: release

      - name: "Upload Release Asset"
        uses: "actions/upload-release-asset@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: ${{ steps.release.outputs.upload_url }} 
          asset_path: ./buttonsmanager.tar.gz
          asset_name: buttonsmanager.tar.gz
          asset_content_type: application/tar+gzip
